# Generated by Django 4.2.2 on 2023-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OKR', '0002_alter_formula_formula_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='formula_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='formula',
            name='formula_value',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='objective',
            name='objective_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_name',
            field=models.CharField(max_length=50),
        ),
    ]
